# -*- coding: utf-8 -*-
"""Web Scrapping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OURTpPcmhiFuc3Wcei1-j7VBXhsA-ZHw
"""

from bs4 import BeautifulSoup
import requests 
import time

print('Write one skills you are not familier with')
unfamilier_skill = input('>')
print(f'Filtering out {unfamilier_skill}')

def find_job():
  html_text = requests.get('https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&txtKeywords=Data+Science&txtLocation=').text
  soup = BeautifulSoup(html_text, 'lxml')
  jobs = soup.find_all('li', class_ = 'clearfix job-bx wht-shd-bx')
  for index, job in enumerate(jobs) :
    published_date = job.find('span', class_ = 'sim-posted').span.text
    if 'few' in published_date:
      company_name = job.find('h3', class_ = 'joblist-comp-name').text
      skills = job.find('span', class_ = 'srp-skills').text.replace(' ','')
      more_info = job.header.h2.a['href']
      if unfamilier_skill not in skills:
        with open(f'/content/drive/MyDrive/posts/{index}.txt','w') as f:
          f.write(f"Company Name : {company_name.strip()}\n")
          f.write(f"Required Skills : {skills.strip()}\n")
          f.write(f"More Info : {more_info}\n")
        print(f'File saved: {index}')

if __name__ == '__main__':
  while True:
    find_job()
    time_wait = 10
    print(f'Waiting {time_wait} minutes...')
    time.sleep(time_wait * 6)

